const languages = [
  [73, 'Afrikaans'],
  [34, 'العربية'],
  [28, 'беларуская'],
  [29, 'Български език'],
  [79, 'বাংলা'],
  [82, 'Bosanski'],
  [4, 'Català'],
  [5, 'Čeština'],
  [43, 'Cymraeg'],
  [6, 'Dansk'],
  [7, 'Deutsch'],
  [27, 'Ελληνικά'],
  [1, 'English'],
  [45, 'Esperanto'],
  [9, 'Español'],
  [51, 'eesti keel'],
  [2, 'فارسی'],
  [23, 'Suomi'],
  [26, 'Wikang Filipino'],
  [8, 'Français'],
  [10, 'Gaeilge'],
  [42, 'Gàidhlig'],
  [69, 'Sprēkō Þiudiskō'],
  [33, 'עברית'],
  [37, 'हिन्दी'],
  [11, 'Hrvatski'],
  [16, 'Magyar'],
  [84, 'Interlingua'],
  [38, 'Bahasa Indonesia'],
  [12, 'Íslenska'],
  [13, 'Italiano'],
  [36, '日本語'],
  [35, '한국어'],
  [41, 'Lingua latina'],
  [87, 'Lëtzebuergesch'],
  [15, 'Lietuvių'],
  [14, 'Latviešu valoda'],
  [46, 'मराठी'],
  [56, 'Bahasa Malaysia'],
  [70, 'Plattdüütsch'],
  [17, 'Nederlands'],
  [18, 'Norsk'],
  [3, 'ਪੰਜਾਬੀ'],
  [19, 'Polski'],
  [20, 'Português brasileiro'],
  [65, 'Português europeu'],
  [76, 'Khuzdul'],
  [50, 'Quenya'],
  [21, 'Română'],
  [30, 'Русский'],
  [75, 'Sindarin'],
  [53, 'Slovenčina'],
  [72, 'Slovenščina'],
  [64, 'af Soomaali'],
  [22, 'Shqip'],
  [31, 'srpski'],
  [25, 'Svenska'],
  [58, 'Kiswahili'],
  [90, 'தமிழ்'],
  [47, 'ไทย'],
  [49, 'tlhIngan-Hol'],
  [48, 'Thermian'],
  [24, 'Türkçe'],
  [32, 'Українська'],
  [44, 'Tiếng Việt'],
  [40, '中文'],
]

export default languages
